import { FC, ReactNode } from "react";
import Head from "next/head";

import Header from "../Header";
import Footer from "../Footer";

import styles from "./Layout.module.scss";

type LayotProps = {
  children: ReactNode;
};

const Layout: FC<LayotProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Good Deeds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.layout}>
        <Header />
        <main className={styles.childrenBlock}>{children}</main>
        <Footer />
      </main>
    </>
  );
};

export default Layout;
