import { FC, ReactNode, useEffect, useState } from "react";
import Head from "next/head";

import Header from "../Header";
import Footer from "../Footer";

import styles from "./Layout.module.scss";
import { useActions, useAppSelector } from "@/store/hooks";
import { useGetUserQuery } from "@/store/api/appApi";
import { User } from "@/store/types";

type LayotProps = {
  children: ReactNode;
};

const Layout: FC<LayotProps> = ({ children }) => {
  const { setCurrentUser } = useActions();
  const { currentUserId } = useAppSelector((store) => store.app);
  const { data: me, isLoading } = useGetUserQuery(currentUserId);

  useEffect(() => {
    setCurrentUser(me as User);
  }, [me]);

  return (
    <>
      <Head>
        <title>Good Deeds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.layout}>
        <Header />
        <main className={styles.childrenBlock}>
          {isLoading ? "Loading" : children}
        </main>
        <Footer />
      </main>
    </>
  );
};

export default Layout;
